In [3]:
import numpy as np

1. Cread tres arrays: de una, dos y tres dimensiones.
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas en algunos casos.
📌 Nota

- El array de 2 dimensiones debe ser de 2 filas y 3 columnas

- El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [49]:
array1 = np.random.randint(50, 250,(5))
array1

array([ 93, 110, 120, 178, 134])

In [50]:
array1.ndim

1

In [57]:
array1.size

5

In [58]:
array1.shape

(5,)

In [61]:
array1.dtype

dtype('int64')

In [53]:
array2 = np.random.rand(2,3)
array2

array([[0.56863715, 0.35292034, 0.18657837],
       [0.71601972, 0.02828753, 0.30579986]])

In [54]:
array2.ndim

2

In [59]:
array2.shape

(2, 3)

In [62]:
array2.size

6

In [63]:
array2.dtype

dtype('float64')

In [55]:
array3 = np.random.randint(0,100,(2,3,5))
array3

array([[[40, 24, 73,  3, 23],
        [27, 20, 97, 70,  9],
        [90, 94, 84, 74, 11]],

       [[51, 36, 13, 63, 84],
        [49, 55, 42, 90, 41],
        [78, 75, 72, 27, 81]]])

In [56]:
array3.ndim

3

In [64]:
array3.size

30

In [65]:
array3.shape

(2, 3, 5)

In [66]:
array3.dtype

dtype('int64')

2. Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [92]:
def consulta_arrays(array):

    print(array.shape)
    print(array.size)
    print(array.ndim)
    print(array.dtype)
    
        

In [93]:
consulta_arrays(array3)

(2, 3, 5)
30
3
int64


3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [68]:
array4 = np.identity(3)
array4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
array4.ndim

2

In [75]:
array4.shape

(3, 3)

4. Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [71]:
array5 = np.ones_like(array3)
array5

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [72]:
array5.ndim

3

5. Es el momento de hacer algunas operaciones entre arrays

- ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?

In [ ]:
#no se puede porque no tienen la misma forma.
#array2 tiene forma 2, 3, mientras que array4 tiene forma 3,3

- En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

In [79]:
array6 = np.ones_like(array4)
array6

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [80]:
np.add(array4, array6)

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

- Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

In [81]:
np.multiply(array6, array4)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- Dividid las dos matricess

In [82]:
np.divide(array6, array4)

/tmp/ipykernel_19150/2723659555.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(array6, array4)


array([[ 1., inf, inf],
       [inf,  1., inf],
       [inf, inf,  1.]])