In [1]:
import numpy as np

1.Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed:

In [2]:
array1 = np.random.rand(2, 3, 5)
array1

array([[[0.54473863, 0.58016151, 0.25234293, 0.7538863 , 0.2197032 ],
        [0.80236181, 0.95455106, 0.56354841, 0.07334469, 0.35812956],
        [0.02141926, 0.65501719, 0.2824734 , 0.05621291, 0.94888565]],

       [[0.63644622, 0.65657567, 0.9341728 , 0.47071886, 0.98752304],
        [0.0171308 , 0.9240374 , 0.23393196, 0.88590188, 0.66989287],
        [0.41172385, 0.84234367, 0.73537493, 0.22472582, 0.98668478]]])

In [3]:
array11 = np.round(array1, 1)
array11

array([[[0.5, 0.6, 0.3, 0.8, 0.2],
        [0.8, 1. , 0.6, 0.1, 0.4],
        [0. , 0.7, 0.3, 0.1, 0.9]],

       [[0.6, 0.7, 0.9, 0.5, 1. ],
        [0. , 0.9, 0.2, 0.9, 0.7],
        [0.4, 0.8, 0.7, 0.2, 1. ]]])

- Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [4]:
media_array = np.mean(array11)
media_array

0.5599999999999999

In [5]:
media_array1 = np.round(media_array, 1)

- Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [6]:
maxi = np.max(array11)

- Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [7]:
mini = np.min(array11)

- Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

In [8]:
array_vacio = np.empty_like(array11, dtype = str) #para poder introducir strings al array, le decimos que sea tipo str
array_vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

TIP: tendréis que hacer unos cuantos bucles for y jugar con los indices de los arrays!

Si el valor del array es igual que la media, se reemplaza por "A".

Si el valor del array es mayor que la media, se reemplaza por "B".

Si el valor del array es menor que la media, se reemplaza por "C".

Si el valor es igual que el máximo, se reemplaza por "D".

Si el valor es igual que el mínimo, se reemplaza por "E".

💡 Pista 💡 Tendréis que iterar por el array y cambiar los valores de la matriz vacía. Para eso tendremos que usar distintos condicionales.

In [9]:
media_array1

0.6

In [17]:
for i in range(0, array11.shape[0]):
    for y in range(0, array11.shape[1]):
        for x in range(0, array11.shape[2]):
            if array11[i][y][x] == media_array1:
                array_vacio[i][y][x] = 'A'
            elif array11[i][y][x] == maxi:
                array_vacio[i][y][x] == 'D'
            elif array11[i][y][x] == mini:
                array_vacio[i][y][x] = 'E'
            elif array11[i][y][x] > media_array1:
                array_vacio[i][y][x] = 'B'
            elif array11[i][y][x] < media_array1:
                array_vacio[i][y][x] = 'C'

In [18]:
array_vacio

array([[['C', 'A', 'C', 'B', 'C'],
        ['B', 'B', 'A', 'C', 'C'],
        ['E', 'B', 'C', 'C', 'B']],

       [['A', 'B', 'B', 'C', 'B'],
        ['E', 'B', 'C', 'B', 'B'],
        ['C', 'B', 'B', 'C', 'B']]], dtype='<U1')

6. Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.


- Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1

- Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2

- Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.

In [62]:
uni_vacio = np.empty(30, dtype=int) #como vamos a introducir integers tenemos que asegurarnos de que sean integers
uni_vacio

array([                  0, 4607182418800017408,                   0,
       4607182418800017408, 4607182418800017408,                   0,
                         0, 4607182418800017408,                   0,
                         0, 4607182418800017408, 4607182418800017408,
       4607182418800017408, 4607182418800017408,                   0,
                         0,                   0,                   0,
                         0, 4607182418800017408, 4607182418800017408,
       4607182418800017408,                   0, 4607182418800017408,
                         0,                   0,                   0,
                         0, 4607182418800017408,                   0])

In [71]:
array_vacio1 = array_vacio.reshape(1,1,30) #para poder compararlos en el bucle, tenemos que dejar a ambos en la misma dimensión
array_vacio1

array([[['C', 'A', 'C', 'B', 'C', 'B', 'B', 'A', 'C', 'C', 'E', 'B',
         'C', 'C', 'B', 'A', 'B', 'B', 'C', 'B', 'E', 'B', 'C', 'B',
         'B', 'C', 'B', 'B', 'C', 'B']]], dtype='<U1')

In [73]:
for i in range(0, array_vacio1.shape[0]):
    for y in range(0, array_vacio1.shape[1]):
        for x in range(0, array_vacio1.shape[2]):
            if array_vacio1[i][y][x] == "A" or array_vacio1[i][y][x] == "B":
                uni_vacio[x] = 1
            elif array_vacio1[i][y][x] == "C" or array_vacio1[i][y][x] == "D":
                uni_vacio[x] = 2
            elif array_vacio1[i][y][x] == "E":
                uni_vacio[x] = 3

In [74]:
uni_vacio

array([2, 1, 2, 1, 2, 1, 1, 1, 2, 2, 3, 1, 2, 2, 1, 1, 1, 1, 2, 1, 3, 1,
       2, 1, 1, 2, 1, 1, 2, 1])

Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [75]:
uni_vacio1 = uni_vacio.reshape (2,3,5)
uni_vacio1

array([[[2, 1, 2, 1, 2],
        [1, 1, 1, 2, 2],
        [3, 1, 2, 2, 1]],

       [[1, 1, 1, 2, 1],
        [3, 1, 2, 1, 1],
        [2, 1, 1, 2, 1]]])