In [1]:
import numpy as np

1. ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [2]:
np.random.seed(1)
arr1 = np.random.sample(4)
arr1

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01])

In [3]:
np.random.seed(1)
arr2 = np.random.sample(4)
arr2

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01])

2. Cread los siguientes arrays:

- Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

In [4]:
uniforme = np.random.uniform(0,10, size = (2,3,5))
uniforme

array([[[1.46755891, 0.92338595, 1.86260211, 3.45560727, 3.96767474],
        [5.38816734, 4.19194514, 6.852195  , 2.0445225 , 8.78117436],
        [0.27387593, 6.7046751 , 4.17304802, 5.58689828, 1.40386939]],

       [[1.98101489, 8.00744569, 9.68261576, 3.13424178, 6.92322616],
        [8.76389152, 8.94606664, 0.85044211, 0.39054783, 1.6983042 ],
        [8.78142503, 0.98346834, 4.21107625, 9.5788953 , 5.33165285]]])

In [5]:
enteros = np.round(uniforme)
enteros

array([[[ 1.,  1.,  2.,  3.,  4.],
        [ 5.,  4.,  7.,  2.,  9.],
        [ 0.,  7.,  4.,  6.,  1.]],

       [[ 2.,  8., 10.,  3.,  7.],
        [ 9.,  9.,  1.,  0.,  2.],
        [ 9.,  1.,  4., 10.,  5.]]])

In [6]:
enteros.size

30

In [7]:
unicos = np.unique(enteros)
unicos

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

- Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

In [8]:
binomial = np.random.binomial(10, 0.3, size = (2,3,5))
binomial

array([[[4, 2, 4, 4, 0],
        [4, 6, 4, 2, 4],
        [1, 3, 5, 2, 2]],

       [[1, 0, 4, 2, 2],
        [3, 1, 3, 1, 3],
        [4, 1, 3, 4, 3]]])

In [9]:
bi_unicos = np.unique(binomial)
bi_unicos

array([0, 1, 2, 3, 4, 5, 6])

3. En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:

⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?

- Elementos comunes entre los dos arrays

In [10]:
enteros

array([[[ 1.,  1.,  2.,  3.,  4.],
        [ 5.,  4.,  7.,  2.,  9.],
        [ 0.,  7.,  4.,  6.,  1.]],

       [[ 2.,  8., 10.,  3.,  7.],
        [ 9.,  9.,  1.,  0.,  2.],
        [ 9.,  1.,  4., 10.,  5.]]])

In [11]:
binomial

array([[[4, 2, 4, 4, 0],
        [4, 6, 4, 2, 4],
        [1, 3, 5, 2, 2]],

       [[1, 0, 4, 2, 2],
        [3, 1, 3, 1, 3],
        [4, 1, 3, 4, 3]]])

In [12]:
intersect = np.intersect1d(enteros, binomial) #nos saca los elementos únicos comunes a ambos arrays
intersect

array([0., 1., 2., 3., 4., 5., 6.])

- Unión de los dos arrays

In [13]:
union = np.union1d(enteros, binomial) #saca los elementos de cada array y los une en orden descendente
union

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

- ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

In [14]:
np.setdiff1d(enteros, bi_unicos)

array([ 7.,  8.,  9., 10.])

4. Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.

- Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

In [15]:
array1 = np.random.randint(1,100,(2,5,8))
array1

array([[[78,  7, 53, 86, 71,  3, 77, 92],
        [22, 76,  8, 78, 73, 76, 77, 44],
        [21, 31, 37,  8, 46, 69, 58, 83],
        [97, 14, 11, 24, 82,  8, 25, 75],
        [93, 21, 33, 13, 66, 95, 61, 25]],

       [[83, 98,  3, 93, 99, 11, 55, 97],
        [83, 87, 71, 67, 72, 49, 55, 16],
        [ 6, 18, 43, 21, 49, 23, 14, 98],
        [54, 85, 11, 97, 56, 62, 57, 90],
        [22, 97, 84, 26, 15, 14, 85, 44]]])

In [16]:
array2 = np.random.randint(1,100,(2,5,8))
array2

array([[[ 7, 78, 57, 60, 16, 25, 10, 67],
        [72, 54, 70, 37, 22, 41, 78, 92],
        [50, 48, 78, 41, 79, 46, 88, 17],
        [29, 46, 68, 67, 79, 47,  1, 30],
        [64, 76, 36, 54, 94, 34,  3, 85]],

       [[84, 49, 55, 33, 29, 56, 83, 32],
        [29, 95, 75,  9, 33,  9, 85, 78],
        [51, 80, 42, 65, 84, 25, 21, 45],
        [16, 31, 92, 15, 20, 27, 87,  8],
        [54, 48, 61, 35, 33, 20, 68, 25]]])

- Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

In [17]:
array3 = np.setdiff1d(array1, array2)
array3

array([ 6, 11, 13, 14, 18, 23, 24, 26, 43, 44, 53, 58, 62, 66, 69, 71, 73,
       77, 82, 86, 90, 93, 97, 98, 99])

- Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

In [18]:
array4 = np.setdiff1d(array2, array1)
array4

array([ 1,  9, 10, 17, 20, 27, 29, 30, 32, 34, 35, 36, 41, 42, 45, 47, 48,
       50, 51, 60, 64, 65, 68, 70, 79, 80, 88, 94])

- Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

In [19]:
array5 = np.in1d(array1, array2) #a partir de booleano nos está comparando elemento a elemento si está o no está.
array5

array([ True,  True, False, False, False,  True, False,  True,  True,
        True,  True,  True, False,  True, False, False,  True,  True,
        True,  True,  True, False, False,  True, False, False, False,
       False, False,  True,  True,  True, False,  True,  True, False,
       False,  True,  True,  True,  True, False,  True, False, False,
       False,  True, False,  True,  True, False,  True,  True,  True,
        True,  True, False, False, False,  True,  True, False, False,
       False,  True,  True, False, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False])

In [20]:
array5.size

80

- ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [26]:
print(array1.size)
print(array2.size)
print(array3.size)
print(array4.size)
print(array5.size)

80
80
25
28
80
