In [31]:
import numpy as np

1. Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:

In [32]:
array1 = np.random.rand(5,3)
array1

array([[0.51790809, 0.00453549, 0.94006433],
       [0.3756266 , 0.69320583, 0.95977917],
       [0.33662172, 0.66418294, 0.37135738],
       [0.30524659, 0.03886508, 0.63767087],
       [0.25673922, 0.78670592, 0.69094567]])

In [33]:
array1.ndim

2

- El valor de la primera fila y la segunda columna.

In [34]:
array1[0,1]

0.004535490286907029

- Los valores de la segunda fila y las dos primeras columnas.

In [35]:
array1[1, :2]

array([0.3756266 , 0.69320583])

- Extraed las filas pares (incluyendo la 0) y todas las columnas.

In [36]:
array1

array([[0.51790809, 0.00453549, 0.94006433],
       [0.3756266 , 0.69320583, 0.95977917],
       [0.33662172, 0.66418294, 0.37135738],
       [0.30524659, 0.03886508, 0.63767087],
       [0.25673922, 0.78670592, 0.69094567]])

In [37]:
array1[::2, :]

array([[0.51790809, 0.00453549, 0.94006433],
       [0.33662172, 0.66418294, 0.37135738],
       [0.25673922, 0.78670592, 0.69094567]])

- Extraed los valores que sean mayores que 0.5.

In [38]:
array1[(array1 > 0.5)]

array([0.51790809, 0.94006433, 0.69320583, 0.95977917, 0.66418294,
       0.63767087, 0.78670592, 0.69094567])

- Extraed los valores menores que 0.2 o mayores que 0.5

In [39]:
array1[(array1 > 0.5) | (array1 < 0.2)]

array([0.51790809, 0.00453549, 0.94006433, 0.69320583, 0.95977917,
       0.66418294, 0.03886508, 0.63767087, 0.78670592, 0.69094567])

2. Cread dos array de tres dimensiones:

- El primero de 2 matrices, 5 filas y 3 columnas.

In [40]:
array2 = np.random.randint(0,100,(2,5,3))
array2

array([[[38, 84, 98],
        [27, 14, 11],
        [59, 25, 71],
        [14, 61, 97],
        [57, 30, 75]],

       [[65, 75,  0],
        [28, 74, 82],
        [15, 86, 66],
        [40,  9, 32],
        [ 9, 13, 29]]])

- El segundo de 3 matrices, 2 filas y 5 columnas

In [41]:
array3 = np.random.randint(0,100,(3,2,5))
array3

array([[[19, 14, 99, 58, 37],
        [ 0, 64, 95, 33, 81]],

       [[91, 45, 33, 83, 85],
        [32, 33, 96, 21, 92]],

       [[88, 47, 87,  1, 87],
        [23, 13, 27, 68, 79]]])

- Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.

In [42]:
def consulta_arrays(array):

    print('Este es el shape', array.shape)
    print('Este es el size', array.size)
    print('Este es el ndim', array.ndim)
    print('ESte es el dtype', array.dtype)

In [43]:
consulta_arrays(array2)

Este es el shape (2, 5, 3)
Este es el size 30
Este es el ndim 3
ESte es el dtype int64


In [44]:
consulta_arrays(array3)

Este es el shape (3, 2, 5)
Este es el size 30
Este es el ndim 3
ESte es el dtype int64


- Sumad los dos arrays. ¿Podéis? ¿Por qué?

In [46]:
sumarrays = np.add(array2, array3)
sumarrays #No se puede sumar porque tienen diferente shape o forma

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

- Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:

- .reshape()

- .transpose()

Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

.reshape()

In [47]:
array_cambiado = np.reshape(array3, (2,5,3))
array_cambiado #es array3 con la forma adecuada para operar junto a array2

array([[[19, 14, 99],
        [58, 37,  0],
        [64, 95, 33],
        [81, 91, 45],
        [33, 83, 85]],

       [[32, 33, 96],
        [21, 92, 88],
        [47, 87,  1],
        [87, 23, 13],
        [27, 68, 79]]])

In [48]:
np.add(array_cambiado, array2) #Se puede operar con ellos 

array([[[ 57,  98, 197],
        [ 85,  51,  11],
        [123, 120, 104],
        [ 95, 152, 142],
        [ 90, 113, 160]],

       [[ 97, 108,  96],
        [ 49, 166, 170],
        [ 62, 173,  67],
        [127,  32,  45],
        [ 36,  81, 108]]])

.transpose()

In [50]:
array2

array([[[38, 84, 98],
        [27, 14, 11],
        [59, 25, 71],
        [14, 61, 97],
        [57, 30, 75]],

       [[65, 75,  0],
        [28, 74, 82],
        [15, 86, 66],
        [40,  9, 32],
        [ 9, 13, 29]]])

In [51]:
array3

array([[[19, 14, 99, 58, 37],
        [ 0, 64, 95, 33, 81]],

       [[91, 45, 33, 83, 85],
        [32, 33, 96, 21, 92]],

       [[88, 47, 87,  1, 87],
        [23, 13, 27, 68, 79]]])

In [56]:
operacionarray = np.transpose(array2, (2,0,1)) #adaptamos array2 a array3
operacionarray

array([[[38, 27, 59, 14, 57],
        [65, 28, 15, 40,  9]],

       [[84, 14, 25, 61, 30],
        [75, 74, 86,  9, 13]],

       [[98, 11, 71, 97, 75],
        [ 0, 82, 66, 32, 29]]])

In [59]:
np.subtract(operacionarray, array3) #ya podemos operar con array2 cambiado

array([[[ 19,  13, -40, -44,  20],
        [ 65, -36, -80,   7, -72]],

       [[ -7, -31,  -8, -22, -55],
        [ 43,  41, -10, -12, -79]],

       [[ 10, -36, -16,  96, -12],
        [-23,  69,  39, -36, -50]]])